### ISSUE TITLE
Calculate readable price from sqrt_ratio_x96 or tick.

### ISSUE THREAD

**Issue by KuTuGu** [0xKitsune/uniswap_v3_math#23]
Is there any consideration for supporting human readable price format?  

Implementation of JS
- [sqrt_ratio_x96_price](https://github.com/thanpolas/univ3prices/blob/main/src/sqrt-price.js#L20)
- [tick_price](https://github.com/thanpolas/univ3prices/blob/main/src/tick-price.js#L17 )

**Comment by 0xOsiris** [comment]
Hey, thank you for opening up an issue! Sounds like a nice feature. We would like to keep uniswap_v3_math to have parity with the v3 math lib in solidity. Definitely open an issue for this on [cfmms-rs](https://github.com/0xKitsune/cfmms-rs). I think this would be a useful feature in this library!

**Comment by KuTuGu** [comment]
Yeah, got it. I took a look and saw that it is already implemented [here](https://github.com/0xKitsune/cfmms-rs/blob/main/src/pool/uniswap_v3.rs#L368). Thanks for reply.
