### ISSUE TITLE
Feat: Bench `ruint` vs `rug` `Integer` vs `U256` on basic operations

### ISSUE THREAD

**Issue by 0xOsiris** [0xKitsune/uniswap_v3_math#29]
Bench `ruint` vs`rug` `Integer` vs `U256` on basic arithmetic operations such as *, /, %, ..etc. Get an idea of which is optimal across the code base as far as speed, and switch all Integer types across the code base.

**Comment by 0xKitsune** [comment]
The lib has been updated to use alloy, closing as completed.
