### ISSUE TITLE
getSqrtRatioAtTick function returns incorrect result

### ISSUE THREAD

**Issue by Code0x2** [0xKitsune/uniswap_v3_math#9]
The function in `tick_math.rs` returns incorrect result [here](https://github.com/0xKitsune/uniswap_v3_math/blob/main/src/tick_math.rs#L75)
```
if (ratio.shr(32) + (ratio % (U256::one().shl(32)))).is_zero() {
    Ok(U256::zero())
} else {
    Ok(U256::one())
}
```
Function can only return one or zero, which is wrong. UniswapV3 code is ratio >> 32 and adding the value instead
`sqrtPriceX96 = uint160((ratio >> 32) + (ratio % (1 << 32) == 0 ? 0 : 1));`

**Comment by 0xKitsune** [comment]
Thanks for catching this! The lib still needs to be tested, feel free to make a PR fixing this if you would like, otherwise, Ill patch it in the interim.

**Comment by Code0x2** [comment]
Sure, fixed it for myself anyways so might as well
